### ISSUE TITLE
Asignando Tareas DATA-dashboard

### ISSUE THREAD

**Issue by Teresitalee** [Laboratoria/scl-2018-05-bc-core-am-datadashboard#8]
vamos asignar las tareas de construcción del sitio.

**Comment by Teresitalee** [comment]
Data_dashboard:
Hemos creado un proyecto de aplicación web , solicitado por la TM ; de Laboratoria sede SCL. 
Se necesita una interfaz gráfica de datos  estilo pizarra en relación acerca de las alumnas y sus avances en los cursos del bootcamp. para ello diseñado las siguientes interfaces:
1- Login : de inicio de sesión usuario
2- menú de navaBar, de navegación.
    - Home: inicio de navegación de la web

    - Alumnas : información general y personal de todas las alumnas de todas las sedes
                       a. se desplegara un data grilla de tabla con la información de las alumnas por filtro
                          con flechas de ascendentes y descendentes. una vez seleccionada la opción se
                         despliega la información solicitada.

    - cursos : información de los avances de cursos con gráficos de los progresos.
                   a. task (tareas)
                   b. avances de los task
                   c. descripción de cada curso

**Comment by nerdale** [comment]
@Teresitalee El issue debe ser en el repositorio de quien forkeo a Laboratoria.
